package com.example.herobattler

import android.os.Bundle
import android.util.Log
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.activityViewModels
import androidx.navigation.fragment.findNavController
import com.example.herobattler.databinding.FragmentDeleteCharacterBinding
import com.example.herobattler.databinding.FragmentNewCharacterBinding

class DeleteCharacter : Fragment() {

    private var _binding: FragmentDeleteCharacterBinding? = null
    private val binding get() = _binding!!

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?): View? {
        //adapt also this name (the class will be autogenerated)
        _binding = FragmentDeleteCharacterBinding.inflate(inflater, container, false)
        return binding.root
    }


    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val model: CharactersModel by activityViewModels()

        binding.buttonDeleteCharacter.setOnClickListener {

            val name: String = binding.characterToDelete.text.toString()

            if(name != null)
            {
                context?.let { it1 ->
                    model.deleteCharacter(name, it1)
                }
            }
        }
    }
}